<?php
/**
 * EditorTypeString
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  UniOne
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Web API
 *
 * All UniOne API methods require HTTPS connection. UniOne accepts HTTP POST requests in JSON format up to 10 megabytes long and returns HTTP response also in JSON. API endpoint (or base URL) depends on which datacenter the user is registered at.
 *
 * The version of the OpenAPI document: 1.76
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace UniOne\Model;
use \UniOne\ObjectSerializer;

/**
 * EditorTypeString Class Doc Comment
 *
 * @category Class
 * @description Editor type, \&quot;html\&quot; or \&quot;visual\&quot;. Default is \&quot;html\&quot;. You can create a template with \&quot;visual\&quot; editor type only in web interface.
 * @package  UniOne
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EditorTypeString
{
    /**
     * Possible values of this enum
     */
    public const HTML = 'html';

    public const VISUAL = 'visual';

    public const UNKNOWN_DEFAULT_OPEN_API = 'unknown_default_open_api';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::HTML,
            self::VISUAL,
            self::UNKNOWN_DEFAULT_OPEN_API
        ];
    }
}


