<?php
/**
 * WebhookDeliveryInfoInteger
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  UniOne
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Web API
 *
 * All UniOne API methods require HTTPS connection. UniOne accepts HTTP POST requests in JSON format up to 10 megabytes long and returns HTTP response also in JSON. API endpoint (or base URL) depends on which datacenter the user is registered at.
 *
 * The version of the OpenAPI document: 1.76
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace UniOne\Model;
use \UniOne\ObjectSerializer;

/**
 * WebhookDeliveryInfoInteger Class Doc Comment
 *
 * @category Class
 * @description Shall detailed delivery info be returned(1) or not(0). When it&#39;s 1, the information about SMTP response and internal delivery status is returned for \&quot;hard_bounced\&quot; and \&quot;soft_bounced\&quot; email statuses; the user agent is returned for \&quot;opened\&quot; and \&quot;clicked\&quot; statuses and URL for \&quot;clicked\&quot; status.
 * @package  UniOne
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WebhookDeliveryInfoInteger
{
    /**
     * Possible values of this enum
     */
    public const NUMBER_0 = 0;

    public const NUMBER_1 = 1;

    public const UNKNOWN_DEFAULT_OPEN_API = 11184809;

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NUMBER_0,
            self::NUMBER_1,
            self::UNKNOWN_DEFAULT_OPEN_API
        ];
    }
}


