<?php
/**
 * WebhookEventFormatString
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  UniOne
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Web API
 *
 * All UniOne API methods require HTTPS connection. UniOne accepts HTTP POST requests in JSON format up to 10 megabytes long and returns HTTP response also in JSON. API endpoint (or base URL) depends on which datacenter the user is registered at.
 *
 * The version of the OpenAPI document: 1.76
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace UniOne\Model;
use \UniOne\ObjectSerializer;

/**
 * WebhookEventFormatString Class Doc Comment
 *
 * @category Class
 * @description Notification format. \&quot;json_post\&quot;(default) or \&quot;json_post_gzip\&quot;.
 * @package  UniOne
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WebhookEventFormatString
{
    /**
     * Possible values of this enum
     */
    public const JSON_POST = 'json_post';

    public const JSON_POST_GZIP = 'json_post_gzip';

    public const UNKNOWN_DEFAULT_OPEN_API = 'unknown_default_open_api';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::JSON_POST,
            self::JSON_POST_GZIP,
            self::UNKNOWN_DEFAULT_OPEN_API
        ];
    }
}


