<?php
/**
 * WebhookDeliveryInfoIntegerTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  UniOne
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Web API
 *
 * All UniOne API methods require HTTPS connection. UniOne accepts HTTP POST requests in JSON format up to 10 megabytes long and returns HTTP response also in JSON. API endpoint (or base URL) depends on which datacenter the user is registered at.
 *
 * The version of the OpenAPI document: 1.76
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace UniOne\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * WebhookDeliveryInfoIntegerTest Class Doc Comment
 *
 * @category    Class
 * @description Shall detailed delivery info be returned(1) or not(0). When it&#39;s 1, the information about SMTP response and internal delivery status is returned for \&quot;hard_bounced\&quot; and \&quot;soft_bounced\&quot; email statuses; the user agent is returned for \&quot;opened\&quot; and \&quot;clicked\&quot; statuses and URL for \&quot;clicked\&quot; status.
 * @package     UniOne
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class WebhookDeliveryInfoIntegerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "WebhookDeliveryInfoInteger"
     */
    public function testWebhookDeliveryInfoInteger()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
