<?php
/**
 * WebhookEventsObjectTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  UniOne
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Web API
 *
 * All UniOne API methods require HTTPS connection. UniOne accepts HTTP POST requests in JSON format up to 10 megabytes long and returns HTTP response also in JSON. API endpoint (or base URL) depends on which datacenter the user is registered at.
 *
 * The version of the OpenAPI document: 1.76
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace UniOne\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * WebhookEventsObjectTest Class Doc Comment
 *
 * @category    Class
 * @description Object containing events to notify of.
 * @package     UniOne
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class WebhookEventsObjectTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "WebhookEventsObject"
     */
    public function testWebhookEventsObject()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "spamBlock"
     */
    public function testPropertySpamBlock()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "emailStatus"
     */
    public function testPropertyEmailStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
