<?php
/**
 * TemplateApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  UniOne
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Web API
 *
 * All UniOne API methods require HTTPS connection. UniOne accepts HTTP POST requests in JSON format up to 10 megabytes long and returns HTTP response also in JSON. API endpoint (or base URL) depends on which datacenter the user is registered at.
 *
 * The version of the OpenAPI document: 1.76
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace UniOne\Test\Api;

use \UniOne\Configuration;
use \UniOne\ApiException;
use \UniOne\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TemplateApiTest Class Doc Comment
 *
 * @category Class
 * @package  UniOne
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TemplateApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for templateDelete
     *
     * Deletes a template by id..
     *
     */
    public function testTemplateDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for templateGet
     *
     * Gets template properties by it's id..
     *
     */
    public function testTemplateGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for templateList
     *
     * Returns the list of all or some templates of the account..
     *
     */
    public function testTemplateList()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for templateSet
     *
     * Creates or updates an email template..
     *
     */
    public function testTemplateSet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
